output "sg-id" {
  value = aws_security_group.eks_cluster_sg.id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = aws_eks_cluster.eks_cluster.endpoint
}


output "certificate_authority" {
  description = "kubectl config as generated by the module."
  value       = aws_eks_cluster.eks_cluster.certificate_authority
}

output "cluster_id" {
  description = "Cluster id."
  value       = aws_eks_cluster.eks_cluster.id
}

output "cluster_name" {
  description = "Cluster name"
  value       = aws_eks_cluster.eks_cluster.name
}
output "cluster_security_group_id" {
  description = "Cluster security group id"
  value       = aws_eks_cluster.eks_cluster.vpc_config[0].cluster_security_group_id
}


